version: '2'
services:
  goutils_test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/github.com/revinate/go-utils
    environment:
      - APP_ENVIRONMENT=dev
    ports:
      - "3001:3001"
    links:
      - etcd
  etcd:
    image: quay.io/coreos/etcd:v2.3.7
    command: -advertise-client-urls=http://0.0.0.0:2379 -listen-client-urls=http://0.0.0.0:2379
